version: "3.7"
networks:
  my_network:

services:
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    image: opensearch-data-prepper:2.0.0-SNAPSHOT
    working_dir: /usr/share/data-prepper/
    command: sh data-prepper-wait-for-os-and-start.sh
    volumes:
      - ./config/data-prepper-wait-for-os-and-start.sh:/usr/share/data-prepper/data-prepper-wait-for-os-and-start.sh
      - ./config/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./config/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ports:
      - "4900:4900" # DataPrepperServer port
      - "21890:21890" # OTelTraceSource port
    networks:
      - my_network
    depends_on:
      - opensearch

  opensearch:
    container_name: node-0.example.com
    image: opensearchproject/opensearch:1.0.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
    networks:
      - my_network

  opensearch-dashboard:
    container_name: opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:1.0.0
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_URL: https://node-0.example.com:9200
      OPENSEARCH_HOSTS: https://node-0.example.com:9200
    networks:
      - my_network

  otel-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector:0.24.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "55680:55680"
    depends_on:
      - data-prepper
    networks:
      - my_network

  # Metric and Trace Sample Data Generator
  ot-metric-emitter:
    container_name: aot-sample
    image: aottestbed/aws-otel-collector-sample-app:java-0.1.0
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=AOCDockerDemo,service.name=AOCDockerDemoService
      - S3_REGION=us-west-2
    depends_on:
      - otel-collector
    networks:
      - my_network
